project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Ronny A. Hernández Mora"
  site-url: https://ronnyale.com/
  repo-url: https://github.com/ronnyhdez/blog/
  open-graph: true
  navbar:
    title: false
    background: "#F5F1ED"
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ronnyhdez/blog
      - icon: twitter
        href: https://twitter.com/ronny_hdezmora
      - icon: person-circle
        href: https://ronnyale.com/
  page-footer:
    center:
      - href: https://ronnyale.com
        text: ronnyale.com

format:
  html:
    theme:
      - flatly
    linkcolor: "#FF5500"
    highlight-style: tango 
    code-line-numbers: true
